# Generated by Django 5.2.10 on 2026-01-11 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('breads', '0010_alter_breadingredient_options_alter_country_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name': 'country of origin', 'verbose_name_plural': 'countries of origin'},
        ),
    ]
