# Generated by Django 5.2.10 on 2026-01-21 20:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_blogpage_body'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='authors',
            field=models.ManyToManyField(blank=True, related_name='authored_blog_pages', to=settings.AUTH_USER_MODEL),
        ),
    ]
