# Generated by Django 5.2.11 on 2026-02-13 16:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_alter_blogpage_body'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='author',
            field=models.ForeignKey(blank=True, help_text='This is an optional field; the author is set to the user who creates the page by default, but can be set to any other user if necessary.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_pages_authored', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='blogpage',
            name='subtitle',
            field=models.CharField(blank=True, help_text='Subtitle for the page', max_length=255),
        ),
    ]
