# Generated by Django 5.2.11 on 2026-02-13 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customimage',
            name='credit',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
