# Generated by Django 5.2.10 on 2026-01-21 22:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0028_mediareleasepage'),
        ('images', '__first__'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standardpage',
            name='og_image',
            field=models.ForeignKey(blank=True, help_text='Shown when linking to this page on social media. If blank, may show an image from the page, or the default from Settings > SEO.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.customimage', verbose_name='Preview image'),
        ),
    ]
